apiVersion: apps/v1
kind: Deployment
metadata:
  name: beanlord
  namespace: beanworld
spec:
  replicas: 1
  selector:
    matchLabels:
      app: beanlord
  template:
    metadata:
      labels:
        app: beanlord
    spec:
      initContainers:
        - name: db-init
          image: beanlord-db-init:1.1
          env:
            - name: DB_HOST
              value: postgres
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: pg-secret
                  key: POSTGRES_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pg-secret
                  key: POSTGRES_PASSWORD
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: pg-secret
                  key: POSTGRES_DB
      containers:
        - name: main
          image: beanlord-main:1.0