apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: beanlord-operator-rb
  namespace: beanworld
subjects:
- kind: ServiceAccount
  name: beanlord-operator-sa
  namespace: beanworld
roleRef:
  kind: Role
  name: beanlord-operator-role
  apiGroup: rbac.authorization.k8s.io