apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: beanworld
  name: beanlord-operator-role
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch", "create"]