FROM golang:1.24.5 as builder

ENV GOOS=linux \
    GOARCH=amd64 \
    CGO_ENABLED=0

WORKDIR /app

COPY go.mod ./
COPY go.sum ./
RUN go mod download

COPY . .

RUN go build -o beanlord

# Final stage
FROM debian:bookworm-slim

WORKDIR /app

COPY --from=builder /app/beanlord .

CMD ["./beanlord"]